name: onlinejudge-api
services:
  postgres-db:
    image: postgres:18.4
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  python-init:
    image: docker:cli
    container_name: python_init
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: docker pull python:3.10-alpine
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onlinejudge_api
    image: duckien185/onlinejudge_api:latest
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sandbox:/app/sandbox
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HOST_SANDBOX_DIR=${PWD}/sandbox
      - ConnectionStrings__PostgreSQLConnection=Host=${DB_HOST};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: always
    env_file:
      - .env

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
volumes:
  postgres_data:
